# Generated by Django 3.2.4 on 2021-06-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_auto_20210623_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='bithdate',
            new_name='bith_date',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='lastame',
            new_name='last_name',
        ),
    ]
