# Generated by Django 3.2.4 on 2021-06-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0005_auto_20210623_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
