# Generated by Django 3.2.4 on 2021-06-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0006_alter_birthday_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='bith_date',
            new_name='birth_date',
        ),
    ]
