# Generated by Django 3.2.4 on 2021-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0007_rename_bith_date_birthday_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
