# Generated by Django 3.2.4 on 2021-06-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0010_alter_birthday_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
